#配置服务端口号
server:
  port: 8300
#eureka相关配置
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/

#配置服务应用名
spring:
  application:
    name: k-shop-picture-server


# 配置FastDFS图片服务器
fdfs:
  soTimeout: 1500
  connectTimeout: 600
  resHost: 192.168.105.249
  storagePort: 8888
  trackerList[0]: 192.168.105.249:22122
  thumbImage:
    height: 150
    width: 150

