#配置服务器端口
server:
  port: 8200
#server.servlet.context-path=/mall
# 配置FreeMarker
spring:
  application:
    name: k-shop-web-service
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html;charset=utf-8
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:templates/
    settings.template_update_delay: 0
    settings.default_encoding: UTF-8
    settings.classic_compatible: true
    settings.date_format: yyyy-MM-dd
    settings.time_format: HH:mm:ss
    settings.datetime_format: yyyy-MM-dd HH:mm:ss
    #数据库druid相关配置
  druid:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/k-shop?characterEncoding=utf-8
      username: root
      password: 123456
      maxActive: 30 #最大连接数
      minIdle: 5    #最小连接数
      maxWait: 10000  #获取连接的最大等待时间
      validationQuery: select 'x'   #解决mysql8小时的问题
      timeBetweenEvicationRunsMills: 600000  #空闲连接检查时间间隔
      minEvictableIdleTimeMills: 300000    #空闲连接最小空闲时间
  #mybatis的配置&&通用Mapper配置
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  #mybatis.config-location=
  type-aliases-package: com.huatech.shop.module.*.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#配置eureka

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/

